# Generated by Django 5.0.4 on 2024-05-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reader_card',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер читательского билета'),
        ),
    ]
