# Generated by Django 5.0.4 on 2024-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Дополнительные данные читателя', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reader_card',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Номер читательского билета'),
        ),
    ]
