# Generated by Django 5.0.4 on 2024-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reader_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер читательского билета'),
        ),
    ]
