# Generated by Django 5.0.4 on 2024-06-14 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('publication_year', models.IntegerField(verbose_name='Год публикации')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('inventory_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True, verbose_name='Дата заимствования')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='Книга продлена (1-да, 0-нет)')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книга')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'выданную книгу',
                'verbose_name_plural': 'Выданные книги',
            },
        ),
    ]
