# Generated by Django 5.0.4 on 2024-05-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_options_alter_borrowedbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'verbose_name': 'Заимствованную книгу', 'verbose_name_plural': 'Заимствованные книги'},
        ),
    ]
