# Generated by Django 5.0.4 on 2024-05-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_is_available_borrowedbook_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращена'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='renewal_count',
            field=models.IntegerField(default=0, verbose_name='Книга продлена (1-да, 0-нет)'),
        ),
    ]
